import React from 'react';
import Head from 'next/head';

export const NestedMetaData = ({ children, metadata }) => {
  return (
    <>
      <Head>
        <title data-testid="title">{metadata.title ? metadata.title : 'MAGENTO PWA'}</title>
        <meta
          name="description"
          content={metadata.description ? metadata.description : 'Generated by create next app'}
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div data-testid="metadata">{children}</div>
    </>
  );
};
